version: '2'
services:
    app:
        build:
            context: .
            dockerfile: ./docker/personal/Dockerfile.app
        ports:
            - "5858:5858"
            - "8080:8080"
        links:
            - redis
        volumes:
            - .:/usr/src/app
    redis:
        image: redis:5.0.3
        ports:
            - "6378:6379"
