version: '2'
services:
    test-app:
        build:
            context: .
            dockerfile: ./docker/test/Dockerfile.app
        links:
            - test-redis:redis
    test-redis:
        image: redis:3.2.4
